import { Ifo } from './types'

const ifos: Ifo[] = [
  // {
  //   id: 'blink',
  //   address: '0x44a9Cc8463EC00937242b660BF65B10365d99baD',
  //   isActive: false,
  //   name: 'BLINk (BLK)',
  //   subTitle: 'Online games on BSC',
  //   description:
  //     'BLINk enables BNB holders to enjoy gaming experiences that WINk users on Tron have been enjoying for over two years.',
  //   launchDate: 'Nov. 20',
  //   launchTime: '9PM SGT',
  //   saleAmount: '100,000,000 BLINK',
  //   raiseAmount: '$1,000,000',
  //   cakeToBurn: '$500,000',
  //   projectSiteUrl: 'https://blink.wink.org',
  //   currency: 'CAKE-BNB LP',
  //   currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
  //   tokenDecimals: 6,
  //   releaseBlockNumber: 3279767,
  // },
  // {
  //   id: 'ditto',
  //   address: '0x570c9eB19553526Fb35895a531928E19C7D20788',
  //   isActive: false,
  //   name: 'Ditto (DITTO)',
  //   subTitle: 'Next-gen elastic supply token',
  //   description:
  //     'Ditto is the first elastic supply token on the Binance Smart Chain. Its goal is to maintain a stable price of $1, where its supply will adapt to changes in demand. All supply changes will apply equally to every wallet holding Ditto, and holders should always have the same % of the total supply',
  //   launchDate: 'Dec. 23',
  //   launchTime: '3PM SGT',
  //   saleAmount: '700,000 DITTO',
  //   raiseAmount: '$630,000',
  //   cakeToBurn: '$315,000',
  //   projectSiteUrl: 'https://ditto.money/',
  //   currency: 'CAKE-BNB LP',
  //   currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
  //   tokenDecimals: 9,
  //   releaseBlockNumber: 3279767,
  // },
  // {
  //   id: 'tenet',
  //   address: '0xB922aA19A2603A07C6C9ED6c236618C9bac51f06',
  //   isActive: false,
  //   name: 'Tenet (TEN)',
  //   subTitle: 'Cross-chain Automated Market Maker',
  //   description:
  //     'Tenet is a cross-chain Automated Market Maker (AMM) connector that provides a decentralized Liquidity Tap for various tokens. The Liquidity Tap is the powerhouse of the Liquidity Pool, employing a dynamic algorithm to give the Liquidity Provider fairer, more efficient, and richer incentives. Tenet aims to build a cross-chain and cross-platform toolkit protocol that allows the demand side to customize the parameters of the liquidity tap, allowing them to reach out to more liquidity participants effectively and with relative ease.',
  //   launchDate: 'Jan. 5',
  //   launchTime: '3PM SGT',
  //   saleAmount: '1,000,000 TEN',
  //   raiseAmount: '$1,000,000',
  //   cakeToBurn: '$500,000',
  //   projectSiteUrl: 'https://www.tenet.farm/',
  //   currency: 'CAKE-BNB LP',
  //   currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
  //   tokenDecimals: 18,
  //   releaseBlockNumber: 3483883,
  // },
  // {
  //   id: 'helmet',
  //   address: '0xa32509d760ee47Eb2Be96D338b5d69B5FBa4eFEB',
  //   isActive: false,
  //   name: 'Helmet.insure (Helmet)',
  //   subTitle: 'Crypto-assets insurance trading platform',
  //   description:
  //     'Helmet is a peer-to-peer insurance protocol written with options trading logic, which allows anyone to create any insurance policy easily in the market. Helmet aims to enable DeFi users to be protected against the risk of price fluctuations by providing price-shield insurance for BSC assets. They provide suppliers with a range of insurance types to sell, giving a variety of hedging strategies to the market.',
  //   launchDate: 'Jan. 13',
  //   launchTime: '5PM SGT',
  //   saleAmount: '10,000,000 Helmet',
  //   raiseAmount: '$1,000,000',
  //   cakeToBurn: '$500,000',
  //   projectSiteUrl: 'https://www.helmet.insure/',
  //   currency: 'CAKE-BNB LP',
  //   currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
  //   tokenDecimals: 18,
  //   releaseBlockNumber: 3771926,
  // },
  // {
  //   id: 'soteria',
  //   address: '0x9C21123D94b93361a29B2C2EFB3d5CD8B17e0A9e',
  //   isActive: true,
  //   name: 'Soteria',
  //   subTitle: 'A blockchain based mutual to share the risk of DeFi on Binance Smart Chain',
  //   description:
  //     'Soteria allows users to buy insurance cover to greatly diminish or reduce the financial risk of hacks. It replaces the idea of a traditional insurance company, because it is wholly owned by the members. The model encourages engagement as members receive economic incentives for participating in Risk Assessment, Claims Assessment and Governance.',
  //   launchDate: 'Jan. 21',
  //   launchTime: '4PM SGT',
  //   saleAmount: '1,500,000 wSOTE',
  //   raiseAmount: '$525,000',
  //   cakeToBurn: '$262,500',
  //   projectSiteUrl: 'https://soteria.finance/#/',
  //   currency: 'CAKE-BNB LP',
  //   currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
  //   tokenDecimals: 18,
  //   releaseBlockNumber: 4086064,
  // },
  {
    id: 'autoshark',
    address: '0x46C84aBBBeB3CA0C2fAc5b37079596517B4E8a6e',
    isActive: true,
    name: 'AutoShark',
    subTitle:
      "AutoShark is the world's 1st Yield Optimizer for Automatic Liquidity Acquisition Farms & AMMs on Binance Smart Chain.",
    description:
      'AutoShark is a Fork from PancakeBunny and similar to how PancakeBunny is to PancakeSwap, AutoShark is able to be built on multiple platforms but to start off, we will build on PantherSwap. The DeFi ecosystem is a robust landscape, with multiple Dapps looking to participate in certain segments of the market. From lending, to gamification, to NFT marketplaces, the goal of AutoShark is to capture interest through the use of yield optimizing for the Binance Smart Chain.\n' +
      'Through automation and auto-compounding, AutoShark allows individuals to reap the benefits of compounding without any additional steps. This makes for a easy way to increase yields on your assets as there will be minimal action taken. There are no hidden fees or extra charges when you get on the platform. Sit back and let AutoShark do the work for you!',
    launchDate: 'May. 18',
    launchTime: '11PM UTC',
    saleAmount: '1,500,000 SHARK',
    raiseAmount: '$1,500,000',
    cakeToBurn: '$750,000',
    projectSiteUrl: 'https://autoshark.finance/',
    currency: 'PANTHER-BNB LP',
    currencyAddress: '0xC24AD5197DaeFD97DF28C70AcbDF17d9fF92a49B',
    tokenDecimals: 18,
    releaseBlockNumber: 7425782,
  },
]

export default ifos
